language: csharp
solution: SpiceSharp.sln

os:
  - linux
  - osx

install:
  - nuget restore

script:
  - msbuild ./SpiceSharp.sln /p:Configuration=Debug
  - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./SpiceSharpTest/bin/Debug/SpiceSharpTest.dll

branches:
  only:
  - master
