configuration:
  - Debug

os: Visual Studio 2017

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

environment:
  CODECOV_TOKEN: 862c0870-53eb-4ed5-9a82-759c70cf78e0

branches:
  only:
    - master

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build_script:
  - msbuild SpiceSharp\SpiceSharp.csproj -p:Configuration=Debug
  - msbuild SpiceSharpTest\SpiceSharpTest.csproj -p:Configuration=Debug
  - OpenCover.Console.exe -register:user -oldStyle -target:"packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe" -targetargs:"SpiceSharpTest\SpiceSharpTest.csproj" -filter:"+[*]* -[SpiceSharpTest*]*" -output:"SpiceSharpCoverage.xml"
  - codecov -f "SpiceSharpCoverage.xml"
  - msbuild SpiceSharp\SpiceSharp.csproj -p:Configuration=Release

artifacts:
  - path: SpiceSharp\bin\Release\*.nupkg
    name: NuGet package
