# This is a basic workflow to help you get started with Actions

name: Linux Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: docker://mono:latest
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Compile Spice#
      run: msbuild SpiceSharp/SpiceSharp.csproj -p:Configuration=Debug

    - name: Compile Spice#.Test
      run: msbuild SpiceSharpTest/SpiceSharpTest.csproj -p:Configuration=Debug
      
    - name: Run tests
      run: dotnet test SpiceSharpTest/bin/Debug/SpiceSharpTest.dll
      
      
