# This is a basic workflow to help you get started with Actions

name: Windows Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup MSBuild environment
      uses: microsoft/setup-msbuild@v1.0.0
          
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore

    - name: Compile Spice#
      run: msbuild SpiceSharp\SpiceSharp.csproj -p:Configuration=Debug

    - name: Compile Spice#.Test
      run: msbuild SpiceSharpTest\SpiceSharpTest.csproj -p:Configuration=Debug
      
    - name: Run tests
      run: dotnet test SpiceSharpTest/bin/Debug/SpiceSharpTest.dll

